### ISSUE TITLE
Add API specification to Endpoints

### ISSUE THREAD

**Issue by Jan222333444** [Jan222333444/EasyContactForms#10]
**Is your feature request related to a problem? Please describe.**
I want to see the api documentation, when the server is running

**Describe the solution you'd like**
Add a endpoint that hosts and renders the OpenAPI documentation

**Additional context**
There is already an Open API specification in the documentations that needs to be updated.

**Comment by uvais724** [comment]
Hi @Jan222333444,
I would like to know in which format you want to see the api documentation ?
Simple json format would work or you need a swagger ui page ?

**Comment by Jan222333444** [comment]
Hi @uvais724 
A Swagger UI page would be the better option.

**Comment by uvais724** [comment]
Hi @Jan222333444,
Raised PR
https://github.com/Jan222333444/EasyContactForms/pull/12
Please review and merge, let me know if there is any problems.

**Comment by Jan222333444** [comment]
Hi @uvais724,
I already merged the PR, there were no problems.
Thank you for your awesome contribution.
