### ISSUE TITLE
Add ping endpoint

### ISSUE THREAD

**Issue by Jan222333444** [Jan222333444/EasyContactForms#23]
**Is your feature request related to a problem? Please describe.**
I want to ping the server to show if it is up and running or not

**Describe the solution you'd like**
Add an endpoint `/ping` which response with the current state (running) as HTTP Response Code (200)

**Additional context**
At this point there are no more states than running, so this can be hardcoded.

**Comment by uvais724** [comment]
Hi @Jan222333444,
this can be hardcoded, but we can also extend the capabilities of this application by adding actuator dependency which comes with /ping and lots of other health metrics out of the box.
Let me know which approach you want to go with.

**Comment by Jan222333444** [comment]
Hi @uvais724,
Using the actuator dependency for the endpoint is a better approach.
However you are free to choose any approach that you feel is suitable for implementing the /ping endpoint.

**Comment by uvais724** [comment]
Hi @Jan222333444,
Created pull request https://github.com/Jan222333444/EasyContactForms/pull/24 
please review and merge.
